FROM python:3.9-slim

WORKDIR /app

# Установка зависимостей
COPY global_requirements.txt .
RUN pip install --no-cache-dir -r global_requirements.txt

{% if local_requirements %}
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
{% endif %}

# Копирование кода сервиса
COPY . .

# Открываем порт
EXPOSE 5000

# --- ИЗМЕНЕНИЕ: Запускаем сгенерированный entrypoint ---
CMD ["python", "entrypoint.py"]