FROM python:3.10-slim

# Отключаем буферизацию (логи сразу в консоль)
ENV PYTHONUNBUFFERED=1
# Добавляем корень в PYTHONPATH, чтобы Python видел папки как модули
ENV PYTHONPATH=/app

WORKDIR /app

# 1. Зависимости (сначала, для кэша Docker)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Код приложения
COPY . .

# 3. Порт и Запуск
EXPOSE 5000
# Запускаем наш новый run.py (бывший entrypoint)
CMD ["python", "run.py"]